
language: objective-c  #1
osx_image: xcode9.2 #2

jobs:
  include:
    - script: xcodebuild clean build test -project FizzBuzz.xcodeproj -scheme FizzBuzz -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO